// <auto-generated />
using System;
using CarApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230316152454_addedToTable")]
    partial class addedToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarApi.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ac2e11d-d7b8-430d-ab32-2582c3b16a22"),
                            Color = "Red",
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 1895f,
                            UserId = new Guid("34af3d8b-4b2a-4317-b254-3206c3a1124f"),
                            Year = 1997
                        },
                        new
                        {
                            Id = new Guid("f87db22f-bbf3-49d5-9d7a-a20a20f2b975"),
                            Color = "Black",
                            Make = "Dodge",
                            Model = "Challenger",
                            Price = 45000f,
                            UserId = new Guid("c2539447-ed58-4e0b-8175-5d7745210a2b"),
                            Year = 2018
                        });
                });

            modelBuilder.Entity("CarApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2539447-ed58-4e0b-8175-5d7745210a2b"),
                            DateOfBirth = new DateTime(1993, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nathaniel.carballo@gmail.com",
                            Name = "Nathaniel Carballo",
                            Password = "NCar10"
                        },
                        new
                        {
                            Id = new Guid("34af3d8b-4b2a-4317-b254-3206c3a1124f"),
                            DateOfBirth = new DateTime(1995, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "img_cruz@gmail.com",
                            Name = "John Cruz",
                            Password = "LongCruz11"
                        });
                });

            modelBuilder.Entity("CarApi.Models.Car", b =>
                {
                    b.HasOne("CarApi.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarApi.Models.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
